### ISSUE TITLE
Estruturação de pastas e atualização do readme.

### ISSUE THREAD

**Issue by fvieir** [matheusvaz-dev/interactive-rating-component#1]
Fala Mateus, como vai?

Conforme deixado o Feedback e orientações no Discord, segue minhas solicitação para estruturação de pastas e atualização do readme.

Qualquer duvida é so chamar.

Forte abraço.

**Comment by matheusvaz-dev** [comment]
Consegui organizar a pasta assets com os arquivos .js, .css e .png/.jpg, além de melhorar um pouco mais ou meu README. Obrigado pelas dicas, Fabrício!
